build:
  date: '@build.date@'
jwt:
  expiration: 1296000000
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
logging:
  file:
    name: ./dog-live.log
  level:
    com:
      samsung:
        security: DEBUG
    org:
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
      sringframework:
        boot: DEBUG
        security: DEBUG
    root: INFO
management:
  health:
    db:
      enabled: true
    default:
      enabled: true
    diskspace:
      enabled: true
  servlet:
    context-path: /manage
pringfox:
  documentation:
    swagger:
      use-model-v3: false
server:
  address: localhost
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  port: 8080
  servlet:
    contextPath: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spa:
  default-file: /dist/index.html


spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true

  devtools:
    livereload:
      enabled: true

  jpa:
    show-sql : true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false
    static-locations: classpath:/dist/



  datasource:
    hikari:
      auth:
        password: 1234
        username: root
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver

      board:
        password: 1234
        username: root
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/board?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver

      community:
        password: 1234
        username: root
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver

      chat:
        password: 1234
        username: root
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver
