build:
  date: '@build.date@'
jwt:
  expiration: 1296000000
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
logging:
  file:
    name: ./dog-live.log
  level:
    org:
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
      sringframework:
        boot: DEBUG
        security: DEBUG
    root: INFO
management:
  health:
    db:
      enabled: true
    default:
      enabled: true
    diskspace:
      enabled: true
  servlet:
    context-path: /manage
pringfox:
  documentation:
    swagger:
      use-model-v3: false
server:
 # address: localhost
  compression:
    enabled: true
  mime-types: application/json,application/xml,text/xml,text/plain,application/javascript,text/css,text/html,text/event-stream
  port: 8080
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore/ssafy.p12
#    key-store-password: doglivedoggi
#    key-alias: ssafy
  #    trust-store: classpath:keystore/ssafy.p12
  #    trust-store-password: doglivedoggi
  servlet:
    contextPath: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#http-server:
#  http:
#    port: 8080

spa:
  default-file: /dist/index.html


profileImg:
  path: C:\Users\multicampus\Desktop\ssafy\공통프로젝트\Doglive\profile_imgs\
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  profiles:
    include:
      - aws
  security:
    user:
      name: "ssafy"
      password: "ssafy"

  oauth2:
    client:
      registration:
        kakao:
          authorization-grant-type: authorization_code
          client-id: f4c6ef3414193da426ed5d863808c7d4
          client-secret: ocpg3oVjb8ysLbrdZNzDWBINfQvbkPB7
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope:
            - profile
            - account_email
          client-authentication-method: POST
          client-name: Kakao

      provider:

        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: http://kapi.kakao.com/v2/user/me
          user-name-attribute: id
  data:
    web:
      pageable:
        one-indexed-parameters: true

  devtools:
    livereload:
      enabled: true

  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql : true
        format_sql : true
        use_sql_comment: true

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false
    static-locations: classpath:/dist/

  datasource:
    hikari:
      auth:
        password: doglivedoggi
        username: doglive
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver

      board:
        password: doglivedoggi
        username: doglive
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/board?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver

      community:
        password: doglivedoggi
        username: doglive
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver

      chat:
        password: doglivedoggi
        username: doglive
        jdbc-url: jdbc:mariadb://i5a501.p.ssafy.io/chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: org.mariadb.jdbc.Driver